name: ClearLag
version: "1.0"
api: ["1.0.0"]
author: PetteriM1
main: idk.plugin.clearlag.Main

commands:
  clearlag:
    description: Run ClearLag
    usage: "/clearlag"
    permission: clearlag.run
permissions:
  clearlag.run:
    description: "Allows player to run ClearLag"
    default: OP
